/** NORA shared screen styles — the pixel-matched design system surface. */
import { StyleSheet } from 'react-native';
import { theme } from '../theme';

/* ============================== STYLES ============================== */
export const s = StyleSheet.create({
  txIconCircleBare: { width: 32, height: 32, borderRadius: 16, backgroundColor: theme.dark, alignItems: 'center', justifyContent: 'center' },
  txBadge: { position: 'absolute', bottom: -3, right: -3, width: 16, height: 16, borderRadius: 8, backgroundColor: theme.surface, borderWidth: 1.5, borderColor: theme.bg, alignItems: 'center', justifyContent: 'center' },
  activityHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginTop: 2 },
  dateRangePill: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 7 },
  dateRangeLabel: { color: theme.text, fontSize: 10.5, fontWeight: '600' },
  trendUp: { color: theme.green, fontSize: 12, fontWeight: '700' },
  analyticsLink: { color: theme.textDimOnDark, fontSize: 11.5, fontWeight: '700' },
  securityBanner: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#EFEDE2', borderRadius: 14, padding: 13, marginTop: 16, marginBottom: 20 },
  securityIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: theme.dark, alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  securityTitle: { color: theme.text, fontWeight: '800', fontSize: 12.5 },
  securitySub: { color: theme.textDim, fontSize: 10.5, marginTop: 2 },

  profileHeadRow: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 16 },
  avatarWrap: { position: 'relative' },
  cameraBadge: { position: 'absolute', bottom: -2, right: -2, width: 20, height: 20, borderRadius: 10, backgroundColor: theme.gold, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: theme.bg },
  verifiedPillDark: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: 'rgba(240,180,41,0.18)', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 2, alignSelf: 'flex-start' },
  verifiedPillDarkLabel: { color: theme.gold, fontSize: 10, fontWeight: '700' },
  overviewBalance: { color: theme.text, fontSize: 20, fontWeight: '900' },
  miniCard: { width: 60, height: 40, borderRadius: 8, backgroundColor: theme.dark, padding: 6, marginLeft: 10 },
  miniCardLabel: { color: theme.textOnDark, fontWeight: '900', fontSize: 9, letterSpacing: 0.5 },
  profilePromo: { flexDirection: 'row', alignItems: 'center', backgroundColor: theme.dark, borderRadius: 16, padding: 16, marginTop: 18, marginBottom: 16 },
  promoTitleDark: { color: theme.textOnDark, fontWeight: '800', fontSize: 13.5 },
  learnMoreBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: theme.gold, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 7, marginLeft: 10 },
  learnMoreBtnLabel: { color: theme.dark, fontWeight: '800', fontSize: 10.5 },

  accountsSubtitle: { color: theme.textDim, fontSize: 11.5, marginTop: 3, maxWidth: 230 },
  accountTileGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14 },
  accountTile: { width: '47.5%', backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 14, alignItems: 'center', paddingVertical: 14 },
  accountTileIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: theme.dark, alignItems: 'center', justifyContent: 'center', marginBottom: 6 },
  accountTileLabel: { color: theme.text, fontWeight: '700', fontSize: 12.5 },
  accountTileSub: { color: theme.textDim, fontSize: 10.5, marginTop: 2 },
  idAvatar: { width: 38, height: 38, borderRadius: 19, backgroundColor: theme.dark, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  idAvatarText: { color: theme.textOnDark, fontWeight: '900', fontSize: 12 },
  verifiedPill: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: 'rgba(30,158,90,0.12)', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 2, alignSelf: 'flex-start' },
  verifiedPillLabel: { color: theme.green, fontSize: 10, fontWeight: '700' },
  idFootnote: { color: theme.textDim, fontSize: 11, marginTop: 6 },
  bankListRow: { flexDirection: 'row', alignItems: 'center', padding: 13, borderBottomWidth: 1, borderBottomColor: theme.border },
  bankListIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#EFEDE2', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  primaryPill: { backgroundColor: theme.pill, borderRadius: 999, paddingHorizontal: 7, paddingVertical: 1.5 },
  primaryPillLabel: { color: theme.goldDeep, fontSize: 9.5, fontWeight: '700' },
  activeDotSmall: { width: 5, height: 5, borderRadius: 2.5, backgroundColor: theme.green },
  activeStatusLabel: { color: theme.green, fontSize: 10.5, fontWeight: '700' },
  fundingGrid: { flexDirection: 'row', gap: 8, marginTop: 10 },
  fundingTile: { flex: 1, backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 12, alignItems: 'center', paddingVertical: 12, paddingHorizontal: 4 },
  fundingTileIcon: { width: 26, height: 26, borderRadius: 13, backgroundColor: theme.dark, alignItems: 'center', justifyContent: 'center', marginBottom: 6 },
  fundingTileLabel: { color: theme.text, fontWeight: '700', fontSize: 10, textAlign: 'center' },
  fundingTileSub: { color: theme.textDim, fontSize: 8.5, marginTop: 2, textAlign: 'center' },
  viewBanksBtn: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: '#EFEDE2', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  viewBanksBtnLabel: { color: theme.text, fontSize: 11, fontWeight: '700' },

  logoBadge: { width: 34, height: 34, borderRadius: 10, backgroundColor: theme.dark, alignItems: 'center', justifyContent: 'center' },
  brandTagline: { color: theme.textDim, fontSize: 9, fontWeight: '600' },
  topBarIcons: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  bellWrap: { width: 36, height: 36, borderRadius: 18, backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, alignItems: 'center', justifyContent: 'center' },
  bellDot: { position: 'absolute', top: 7, right: 8, width: 6, height: 6, borderRadius: 3, backgroundColor: theme.gold },
  greetingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginTop: 16 },
  greetingLight: { color: theme.textDim, fontSize: 15 },
  greetingName: { color: theme.dark, fontSize: 20, fontWeight: '900' },
  oneNetworkText: { color: theme.dark, fontSize: 10, fontWeight: '700', textAlign: 'right', lineHeight: 15, maxWidth: 120 },
  activePill: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: 'rgba(240,180,41,0.18)', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  activePillLabel: { color: theme.gold, fontSize: 11, fontWeight: '700' },
  tileSub: { color: theme.textDimOnDark, fontSize: 9.5, marginTop: 2, textAlign: 'center' },
  tileIconCircle: { width: 30, height: 30, borderRadius: 15, backgroundColor: theme.textOnDark, alignItems: 'center', justifyContent: 'center', marginBottom: 6 },
  promoCard: { backgroundColor: '#EFEDE2', borderRadius: 18, padding: 18, marginTop: 14 },
  promoTitle: { color: theme.dark, fontWeight: '900', fontSize: 16, lineHeight: 21 },
  exploreBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: theme.gold, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 8, alignSelf: 'flex-start', marginTop: 12 },
  exploreBtnLabel: { color: theme.dark, fontWeight: '800', fontSize: 12 },
  txIconCircle: { width: 32, height: 32, borderRadius: 16, backgroundColor: theme.dark, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  txStatusLabel: { color: theme.green, fontSize: 10.5, fontWeight: '700' },
  sendSubtitle: { color: theme.textDim, fontSize: 11.5, marginTop: 1 },
  sendPromo: { backgroundColor: theme.dark, borderRadius: 16, padding: 16, marginBottom: 14 },
  sendPromoLabel: { color: theme.gold, fontSize: 11, fontWeight: '700' },
  sendPromoTitle: { color: theme.textOnDark, fontSize: 19, fontWeight: '900', marginTop: 6, lineHeight: 24 },
  sendPromoSub: { color: theme.textDimOnDark, fontSize: 12, marginTop: 6 },
  modeRow: { flexDirection: 'row', gap: 6, marginBottom: 16 },
  modeChip: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, borderRadius: 10, paddingVertical: 9, paddingHorizontal: 4, backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border },
  modeChipOn: { backgroundColor: theme.dark, borderColor: theme.dark },
  modeChipLabel: { color: theme.textDim, fontSize: 10, fontWeight: '700' },
  modeChipOnLabel: { color: theme.textOnDark },
  sendToCard: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: theme.border, borderRadius: 14, padding: 13, marginBottom: 8, backgroundColor: theme.surface },
  sendToCardOn: { borderColor: theme.green, backgroundColor: 'rgba(30,158,90,0.06)' },
  sendToCardIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#EFEDE2', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  sendToCardIconOn: { backgroundColor: theme.green },
  contactBtn: { width: 46, borderRadius: 12, borderWidth: 1, borderColor: theme.border, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.surface },
  currencyPill: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 13 },
  currencyPillLabel: { color: theme.text, fontWeight: '700', fontSize: 13 },
  rateBox: { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: '#F1EFE6', borderRadius: 12, padding: 13, marginTop: 14, marginBottom: 6 },
  rateLabel: { color: theme.textDim, fontSize: 10.5 },
  rateValue: { color: theme.text, fontSize: 12, fontWeight: '700', marginTop: 2 },
  input: { backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 12, color: theme.text, paddingHorizontal: 14, paddingVertical: 13, fontSize: 15 },

  page: { flex: 1, backgroundColor: theme.bg },
  pageInner: { padding: 18, paddingBottom: 120 },
  logoWrap: { alignItems: 'center', marginVertical: 36 },
  logoMark: { fontSize: 30, color: theme.gold },
  logo: { fontSize: 34, fontWeight: '900', letterSpacing: 4, color: theme.dark, marginTop: 4 },
  logoSub: { color: theme.textDim, fontSize: 11, fontWeight: '700', marginTop: 2 },
  tagline: { color: theme.textDim, marginTop: 10, fontSize: 13 },
  topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  brandMark: { fontSize: 18, color: theme.gold },
  brandWord: { fontSize: 16, fontWeight: '900', letterSpacing: 1.5, color: theme.dark },
  brandWordSmall: { fontSize: 12, fontWeight: '900', letterSpacing: 1, color: theme.gold },
  bell: { fontSize: 18 },
  greeting: { color: theme.text, fontSize: 20, fontWeight: '800', marginTop: 16 },
  greetingSub: { color: theme.textDim, fontSize: 13, marginTop: 2 },
  screenTitle: { color: theme.text, fontSize: 20, fontWeight: '800' },
  cardTitle: { color: theme.text, fontSize: 17, fontWeight: '800', marginTop: 8, marginBottom: 4 },
  darkLabel: { color: theme.textDimOnDark, fontSize: 12, fontWeight: '700' },
  darkBalance: { color: theme.textOnDark, fontSize: 30, fontWeight: '900', marginTop: 8 },
  darkChevron: { color: theme.textDimOnDark, fontSize: 18 },
  idRow: { flexDirection: 'row', alignItems: 'center', marginTop: 14, gap: 6 },
  activeDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: theme.gold },
  idText: { color: theme.textDimOnDark, fontSize: 12, flex: 1 },
  idTextSmall: { color: theme.textDimOnDark, fontSize: 11, marginTop: 2 },
  activeLabel: { color: theme.gold, fontSize: 12, fontWeight: '700' },
  tileRow: { flexDirection: 'row', gap: 10, marginTop: 14 },
  tile: { flex: 1, backgroundColor: theme.dark, borderRadius: 16, alignItems: 'center', paddingVertical: 16 },
  tileEmoji: { fontSize: 18, color: theme.gold },
  tileLabel: { color: theme.textOnDark, fontWeight: '700', marginTop: 6, fontSize: 11.5 },
  promoText: { color: theme.textOnDark, fontWeight: '800', fontSize: 14 },
  promoSub: { color: theme.textDimOnDark, fontSize: 12, marginTop: 4 },
  sectionTitle: { color: theme.text, fontWeight: '800', fontSize: 14 },
  link: { color: theme.goldDeep, fontWeight: '700', fontSize: 13 },
  empty: { color: theme.textDim, fontSize: 14 },
  txRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: theme.border },
  txFlag: { fontSize: 20, marginRight: 12 },
  txTitle: { color: theme.text, fontWeight: '700', fontSize: 13.5 },
  txSub: { color: theme.textDim, fontSize: 11.5, marginTop: 2 },
  txAmount: { color: theme.text, fontWeight: '800', fontSize: 13.5, marginBottom: 4 },
  sendHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  backArrow: { fontSize: 20, color: theme.text, width: 30 },
  segment: { flexDirection: 'row', backgroundColor: theme.surface, borderRadius: 12, borderWidth: 1, borderColor: theme.border, padding: 4, marginBottom: 16 },
  segmentBtn: { flex: 1, alignItems: 'center', paddingVertical: 10, borderRadius: 9 },
  segmentOn: { backgroundColor: theme.dark },
  segmentLabel: { color: theme.textDim, fontWeight: '700', fontSize: 13 },
  segmentOnLabel: { color: theme.textOnDark },
  sendToRow: { flexDirection: 'row', alignItems: 'center', padding: 14, borderBottomWidth: 1, borderBottomColor: theme.border },
  sendToIcon: { fontSize: 18, marginRight: 12 },
  rowTitleStrong: { color: theme.text, fontWeight: '700', fontSize: 14 },
  rowSubtle: { color: theme.textDim, fontSize: 12, marginTop: 2 },
  radio: { fontSize: 16, color: theme.border },
  radioOn: { color: theme.gold },
  resolvedBox: { backgroundColor: 'rgba(30,158,90,0.08)', borderRadius: 12, padding: 12, marginVertical: 4, marginBottom: 14, borderWidth: 1, borderColor: 'rgba(30,158,90,0.25)' },
  resolvedName: { color: theme.text, fontWeight: '800', fontSize: 14 },
  quoteBox: { backgroundColor: theme.pill, borderRadius: 12, padding: 12, marginVertical: 4, marginBottom: 14 },
  quoteLine: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 },
  quoteLabel: { color: theme.textDim, fontSize: 13 },
  quoteValue: { color: theme.text, fontSize: 13, fontWeight: '800' },
  receiptAmount: { color: theme.text, fontSize: 26, fontWeight: '900', marginVertical: 4 },
  receiptRef: { color: theme.textDim, fontSize: 12, marginBottom: 8 },
  countryRow: { flexDirection: 'row', gap: 8, marginBottom: 14 },
  countryBtn: { flex: 1, borderRadius: 12, paddingVertical: 12, alignItems: 'center', borderWidth: 1, borderColor: theme.border },
  countryOn: { backgroundColor: theme.pill, borderColor: theme.gold },
  countryLabel: { color: theme.textDim, fontWeight: '700', fontSize: 12.5 },
  countryOnLabel: { color: theme.goldDeep },
  switchMode: { color: theme.goldDeep, textAlign: 'center', marginTop: 14, fontWeight: '600', fontSize: 13 },
  footNote: { color: theme.textDim, fontSize: 11, textAlign: 'center', marginTop: 14, lineHeight: 16 },
  avatar: { width: 56, height: 56, borderRadius: 28, backgroundColor: theme.dark, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  avatarText: { color: theme.gold, fontWeight: '900', fontSize: 18 },
  profileName: { color: theme.text, fontSize: 17, fontWeight: '800' },
  fieldLabelX: { color: theme.textDim, fontSize: 12, fontWeight: '700', marginBottom: 6, letterSpacing: 0.3 },
  bankRow: { paddingVertical: 12, paddingHorizontal: 14, borderRadius: 12, borderWidth: 1, borderColor: theme.border, marginBottom: 6, backgroundColor: theme.surface },
  bankRowOn: { backgroundColor: theme.pill, borderColor: theme.gold },
  bankLabel: { color: theme.textDim, fontSize: 14 },
  bankRowOnLabel: { color: theme.goldDeep, fontWeight: '700' },
  filterRow: { flexDirection: 'row', gap: 8, marginTop: 4, flexWrap: 'wrap' },
  filterChip: { paddingHorizontal: 13, paddingVertical: 7, borderRadius: 999, borderWidth: 1, borderColor: theme.border, backgroundColor: theme.surface },
  filterChipOn: { backgroundColor: theme.dark, borderColor: theme.dark },
  filterChipLabel: { color: theme.textDim, fontSize: 12, fontWeight: '700' },
  filterChipOnLabel: { color: theme.textOnDark },
  addRow: { padding: 14, alignItems: 'center' },
  addRowLabel: { color: theme.goldDeep, fontWeight: '700', fontSize: 13 },
});
